//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:00:41 AM GMT 
//


package anji.ipc.flv.jaxb.map;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the anji.ipc.flv.map package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: anji.ipc.flv.map
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocationLinkType }
     * 
     */
    public LocationLinkType createLocationLinkType() {
        return new LocationLinkType();
    }

    /**
     * Create an instance of {@link LocationTypeType }
     * 
     */
    public LocationTypeType createLocationTypeType() {
        return new LocationTypeType();
    }

    /**
     * Create an instance of {@link PointType }
     * 
     */
    public PointType createPointType() {
        return new PointType();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link PathType }
     * 
     */
    public PathType createPathType() {
        return new PathType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link LocationLinkType.AllowedOperation }
     * 
     */
    public LocationLinkType.AllowedOperation createLocationLinkTypeAllowedOperation() {
        return new LocationLinkType.AllowedOperation();
    }

    /**
     * Create an instance of {@link LocationTypeType.AllowedOperation }
     * 
     */
    public LocationTypeType.AllowedOperation createLocationTypeTypeAllowedOperation() {
        return new LocationTypeType.AllowedOperation();
    }

    /**
     * Create an instance of {@link PointType.OutgoingPath }
     * 
     */
    public PointType.OutgoingPath createPointTypeOutgoingPath() {
        return new PointType.OutgoingPath();
    }

}
